export const APPLICATION_LOAD = 'APPLICATION_LOAD';
export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_USER = 'ADD_USER';
export const REMOVE_GUEST_USER = 'REMOVE_GUEST_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const ROOMS_LOADED = 'ROOMS_LOADED';
export const START_MEETING = 'START_MEETING';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const UPDATE_FLOOR = 'UPDATE_FLOOR';
export const SET_THEMES = 'SET_THEMES';
export const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID';
export const SET_CURRENT_FLOOR_ID = 'SET_CURRENT_FLOOR_ID';
export const SET_BACKUP_FLOOR_ID = 'SET_BACKUP_FLOOR_ID';
export const SET_FLOORPLAN_TRANSFORMS = 'SET_FLOORPLAN_TRANSFORMS';
export const UPDATE_OR_ADD_DEPARTMENT = 'UPDATE_OR_ADD_DEPARTMENT';
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const REMOVE_DEPARTMENT = 'REMOVE_DEPARTMENT';
export const REMOVE_FLOOR = 'REMOVE_FLOOR';
export const SET_FLOORS = 'SET_FLOORS';
export const SET_MAX_OCCUPANCY = 'SET_MAX_OCCUPANCY';
export const SET_PINNED_OFFICES = 'SET_PINNED_OFFICES';
export const DISPLAY_ADMIN_TOOL = 'DISPLAY_ADMIN_TOOL';
// this is the flag that determines if the turtle shows that says: admins only
export const SET_ADMIN_ONLY_MODE = 'SET_ADMIN_TOOL';
export const SET_SELF_REGISTRATION = 'SET_SELF_REGISTRATION';



